import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "The blog - Este é um blog com next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="qualquer">
        <header><h1>Header</h1></header>
        {children}
        <footer><h1>Footer</h1></footer>
      </body>
    </html>
  );
}
